USE PRE01
GO

DECLARE @ID AS VARCHAR(10)

SET @ID='012134'

SELECT  *
FROM    dbo.RM00101
WHERE   CUSTNMBR = @ID

--UPDATE  dbo.RM00101
--SET     CUSTNAME = 'JUAN PABLO ALMONTE MONSANTO',
--        CNTCPRSN = 'IDEDA SRL',
--        STMTNAME = 'JUAN PABLO ALMONTE MONSANTO',
--        SHRTNAME = 'JUAN PABLO'
--WHERE   CUSTNMBR = @ID

SELECT  *
FROM    dbo.RM00101
WHERE   CUSTNMBR = @ID

--00000000000000000000000000000000000000000000000000000000000------------------------
/*
go
UPDATE DYNPRE01_PRA_MASTER
SET	PRACUSTNAME = LEFT(RTRIM(A.CUSTNAME) +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN ' // '
			ELSE ''
		END +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN LTRIM(RTRIM(SUBSTRING(PRACUSTNAME, CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) + 1, 20)))
			ELSE ''
		END, 58),
	PRACUSTADD = LEFT(RTRIM([ADDRESS1]) + ' ' + a.ADDRESS2, 90),
	PRACUSTPHONE = LEFT([PHONE1], 20),
	PRACUSTPHONE2 = LEFT([PHONE2], 20),
	PRACUSTID = LEFT([USERDEF1], 20),
	PRACUSTEMAIL = ltrim(rtrim(LEFT(ISNULL(B.Email_Recipient, ''), 90)))
FROM PRE01.dbo.RM00101 AS A
INNER JOIN DYNPRE01_PRA_MASTER
	ON A.CUSTNMBR = DYNPRE01_PRA_MASTER.PRACUSTNMBR
LEFT OUTER JOIN (SELECT
	CUSTNMBR,
	Email_Recipient
FROM PRE01.dbo.RM00106
WHERE (Email_Type = 1)) AS B
	ON A.CUSTNMBR = B.CUSTNMBR
WHERE A.CUSTPRIORITY<50	 





UPDATE DYNPRE01_PRA_MASTER
SET	PRABENEFNAME = LEFT(RTRIM(A.CUSTNAME) +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN ' // '
			ELSE ''
		END +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN LTRIM(RTRIM(SUBSTRING(PRACUSTNAME, CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) + 1, 20)))
			ELSE ''
		END, 58),
	PRABENEADD = LEFT(RTRIM([ADDRESS1]) + ' ' + a.ADDRESS2, 90),
	PRABENEPHONE = LEFT([PHONE1], 20),
	PRABENEPHONE1 = LEFT([PHONE2], 20),
	PRABENEFID = LEFT([USERDEF1], 20),
	PRABENEFEMAIL = ltrim(rtrim(LEFT(ISNULL(B.Email_Recipient, ''), 90)))
FROM PRE01.dbo.RM00101 AS A
INNER JOIN DYNPRE01_PRA_MASTER
	ON A.CUSTNMBR = DYNPRE01_PRA_MASTER.PRABENEFNMBR
LEFT OUTER JOIN (SELECT
	CUSTNMBR,
	Email_Recipient
FROM PRE01.dbo.RM00106
WHERE (Email_Type = 1)) AS B
	ON A.CUSTNMBR = B.CUSTNMBR
	WHERE A.CUSTPRIORITY<50	 

GO

UPDATE DYNBLA01_PRA_MASTER
SET	PRACUSTNAME = LEFT(RTRIM(A.CUSTNAME) +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN ' // '
			ELSE ''
		END +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN LTRIM(RTRIM(SUBSTRING(PRACUSTNAME, CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) + 1, 20)))
			ELSE ''
		END, 58),
	PRACUSTADD = LEFT(RTRIM([ADDRESS1]) + ' ' + a.ADDRESS2, 90),
	PRACUSTPHONE = LEFT([PHONE1], 20),
	PRACUSTPHONE2 = LEFT([PHONE2], 20),
	PRACUSTID = LEFT([USERDEF1], 20),
	PRACUSTEMAIL = ltrim(rtrim(LEFT(ISNULL(B.Email_Recipient, ''), 90)))
FROM BLA01.dbo.RM00101 AS A
INNER JOIN DYNBLA01_PRA_MASTER
	ON A.CUSTNMBR = DYNBLA01_PRA_MASTER.PRACUSTNMBR
LEFT OUTER JOIN (SELECT
	CUSTNMBR,
	Email_Recipient
FROM BLA01.dbo.RM00106
WHERE (Email_Type = 1)) AS B
	ON A.CUSTNMBR = B.CUSTNMBR
	WHERE A.CUSTPRIORITY<50




GO

UPDATE DYNBLA01_PRA_MASTER
SET	PRABENEFNAME = LEFT(RTRIM(A.CUSTNAME) +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN ' // '
			ELSE ''
		END +
		CASE
			WHEN CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) > 0 THEN LTRIM(RTRIM(SUBSTRING(PRACUSTNAME, CHARINDEX('/', REPLACE(PRACUSTNAME, '//', '/')) + 1, 20)))
			ELSE ''
		END, 58),
	PRABENEADD = LEFT(RTRIM([ADDRESS1]) + ' ' + a.ADDRESS2, 90),
	PRABENEPHONE = LEFT([PHONE1], 20),
	PRABENEPHONE1 = LEFT([PHONE2], 20),
	PRABENEFID = LEFT([USERDEF1], 20),
	PRABENEFEMAIL = ltrim(rtrim(LEFT(ISNULL(B.Email_Recipient, ''), 90)))
FROM BLA01.dbo.RM00101 AS A
INNER JOIN DYNBLA01_PRA_MASTER
	ON A.CUSTNMBR = DYNBLA01_PRA_MASTER.PRABENEFNMBR
LEFT OUTER JOIN (SELECT
	CUSTNMBR,
	Email_Recipient
FROM BLA01.dbo.RM00106
WHERE (Email_Type = 1)) AS B
	ON A.CUSTNMBR = B.CUSTNMBR
	WHERE A.CUSTPRIORITY<50	 



GO


update DYNBLA01_PRA_MASTER
set PRACUSTNAME = REPLACE(PRACUSTNAME,'  ',' ')

UPDATE DYNBLA01_PRA_MASTER
SET PRACUSTNAME = REPLACE(PRACUSTNAME, '  ', ' ')

UPDATE DYNBLA01_PRA_MASTER
SET PRACUSTNAME = REPLACE(PRACUSTNAME, '//', '/')

UPDATE DYNBLA01_PRA_MASTER
SET PRACUSTNAME = REPLACE(PRACUSTNAME, '/ /', '/')




UPDATE DYNPRE01_PRA_MASTER
SET PRACUSTNAME = REPLACE(PRACUSTNAME, '  ', ' ')

UPDATE DYNPRE01_PRA_MASTER
SET PRACUSTNAME = REPLACE(PRACUSTNAME, '  ', ' ')

UPDATE DYNPRE01_PRA_MASTER
SET PRACUSTNAME = REPLACE(PRACUSTNAME, '//', '/')

UPDATE DYNPRE01_PRA_MASTER
SET PRACUSTNAME = REPLACE(PRACUSTNAME, '/ /', '/')
*/